name: Build TTS file
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load XML
        id: xml
        uses: andstor/file-reader-action@v1.0.0
        with:
          path: "ui.xml"
      - name: Parse XML into JSON
        uses: jossef/action-set-json-field@v2.1
        with: 
          file: 'tts.json'
          field: 'XmlUI'
          value: ${{ steps.xml.outputs.contents }}
      - name: Load LUA
        id: lua
        uses: andstor/file-reader-action@v1.0.0
        with:
          path: "script.lua"
      - name: Parse LUA into JSON
        uses: jossef/action-set-json-field@v2.1
        with: 
          file: 'tts.json'
          field: 'LuaScript'
          value: ${{ steps.lua.outputs.contents }}
      - uses: actions/upload-artifact@v3
        with:
          name: tts.json
          path: tts.json
