name: Build TTS file
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load XML
        id: xml
        uses: andstor/file-reader-action@v1.0.0
        with:
          path: "ui.xml"
      - name: Parse XML into JSON
        run: echo "`jq '.XmlUI="${steps.xml.outputs.contents}"' tts.json`" > tts.json
      - name: Load LUA
        id: xml
        uses: andstor/file-reader-action@v1.0.0
        with:
          path: "script.lua"
      - name: Parse LUA into JSON
        run: echo "`jq '.LuaScript="${steps.xml.outputs.contents}"' tts.json`" > tts.json
      - uses: actions/upload-artifact@v3
        with:
          name: tts.json
          path: tts.json
